### ISSUE TITLE
回复机器人的某条消息时自动操作消息对应的 issue/pr

### ISSUE THREAD

**Issue by bytemain** [opensumi/github-bot#2]
如果可以的话，可以以当前用户的身份直接回复那个 issue 之类的。

不过卡点应该是在钉钉机器人这，它好像没有回复能力。

我们可以通过点击：

[点我关闭该 issue]()

然后自动发送 `/close issue 123` 之类的

**Comment by lengthmin** [comment]
点击发消息可以这么发送：

帮助信息如下：
[ding_helper](dtmd://dingtalkclient/sendMessage?content=ding_helper) 查看帮助
[markdown](dtmd://dingtalkclient/sendMessage?content=markdown) 发送 markdown
[actionCardSingleBtn](dtmd://dingtalkclient/sendMessage?content=actionCardSingleBtn)
[actionCard](dtmd://dingtalkclient/sendMessage?content=actionCard)
[feedCard](dtmd://dingtalkclient/sendMessage?content=feedCard)
[atme](dtmd://dingtalkclient/sendMessage?content=atme)
[image](dtmd://dingtalkclient/sendMessage?content=image)
[t](dtmd://dingtalkclient/sendMessage?content=t)
[code](dtmd://dingtalkclient/sendMessage?content=code) 发送代码
[test_message](dtmd://dingtalkclient/sendMessage?content=test_message)
[hello](dtmd://dingtalkclient/sendMessage?content=hello)
[webhook](dtmd://dingtalkclient/sendMessage?content=webhook)

**Comment by lengthmin** [comment]
看了一下钉钉的回复事件，它能接收到回复某条消息的信息，但是只有一个字段：`originalMsgId`，这样根本拿不到那条消息的内容..
